services:
  crypto-pulse:
    build:
      context: .
    command: ["./main", "serve"]
    container_name: crypto-pulse
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    env_file:
      - .env
    # share stocklist.json with the container
    volumes:
      - ./stocklist.json:/src/stocklist.json
      - ./crypto-pulse.log:/src/crypto-pulse.log
    networks:
      - cryptopulse_network
    restart: unless-stopped
    profiles:
      - crypto-pulse-app

  finviz-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./main", "finviz-scraper"]
    container_name: finviz-scraper
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    networks:
      - cryptopulse_network
    profiles:
      - finviz-scraper-app
      
  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   ports:
  #     - 51432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
    # profiles:
    #   - database

  crypto-pulse-influxdb:
    image: influxdb:2.1
    container_name: crypto-pulse-influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - cryptopulse_network
    profiles:
      - database

  crypto-pulse-mongodb:
    image: mongo:latest
    container_name: crypto-pulse-mongodb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cryptopulse_network
    profiles:
      - database

volumes:
  postgres:
    driver: local
  influxdb:
    driver: local
  mongodb_data:
    driver: local

networks:
  cryptopulse_network:
    driver: bridge
