version: '3.8'

services:
  stock-screening-app:
    build: .
    container_name: stock_screening_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: app
    command: flask run --host=0.0.0.0 --port=5000