services:
  # server:
  #   build:
  #     context: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   environment:
  #     LOG_LEVEL: debug
  #     LOG_TEXTLOGGING: "true"
  #     #PORT: 3000
  #     DB_ADDR: postgres:51432
  #     #DB_USER: postgres
  #     #DB_PASSWORD: postgres
  #     #DB_DATABASE: postgres
      
  postgres:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 51432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  influxdb:
    image: influxdb:2.1
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: influxdb
      INFLUXDB_USER: influxdb
      INFLUXDB_USER_PASSWORD: influxdb

volumes:
  postgres:
  influxdb:
