services:
  server:
    build:
      context: .
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    env_file:
      - .env
    # share stocklist.json with the container
    volumes:
      - ./stocklist.json:/src/stocklist.json
    networks:
      - cryptopulse_network
    restart: unless-stopped
      
  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   ports:
  #     - 51432:5432
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres

  influxdb:
    image: influxdb:2.1
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - cryptopulse_network

volumes:
  postgres:
  influxdb:

networks:
  cryptopulse_network:
    driver: bridge
