# Generated by Django 5.0.1 on 2024-01-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("price_open", models.DecimalField(decimal_places=16, max_digits=26)),
                ("price_high", models.DecimalField(decimal_places=16, max_digits=26)),
                ("price_low", models.DecimalField(decimal_places=16, max_digits=26)),
                ("price_close", models.DecimalField(decimal_places=16, max_digits=26)),
                ("volume", models.DecimalField(decimal_places=4, max_digits=14)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("m1", models.BooleanField(default=False)),
                ("m3", models.BooleanField(default=False)),
                ("m5", models.BooleanField(default=False)),
                ("m15", models.BooleanField(default=False)),
                ("m30", models.BooleanField(default=False)),
                ("m45", models.BooleanField(default=False)),
                ("h1", models.BooleanField(default=False)),
                ("h2", models.BooleanField(default=False)),
                ("h4", models.BooleanField(default=False)),
                ("h8", models.BooleanField(default=False)),
                ("h12", models.BooleanField(default=False)),
                ("h16", models.BooleanField(default=False)),
                ("d1", models.BooleanField(default=False)),
                ("d2", models.BooleanField(default=False)),
                ("d3", models.BooleanField(default=False)),
                ("d4", models.BooleanField(default=False)),
                ("d5", models.BooleanField(default=False)),
                ("d6", models.BooleanField(default=False)),
                ("w1", models.BooleanField(default=False)),
                ("w2", models.BooleanField(default=False)),
                ("w3", models.BooleanField(default=False)),
                ("w4", models.BooleanField(default=False)),
            ],
        ),
    ]
