# Generated by Django 5.0.1 on 2024-01-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockdata",
            index=models.Index(
                fields=[
                    "m1",
                    "m3",
                    "m5",
                    "m15",
                    "m30",
                    "m45",
                    "h1",
                    "h2",
                    "h4",
                    "h8",
                    "h12",
                    "h16",
                    "d1",
                    "d2",
                    "d3",
                    "d4",
                    "d5",
                    "d6",
                    "w1",
                    "w2",
                    "w3",
                    "w4",
                ],
                name="screener_st_m1_e43f8c_idx",
            ),
        ),
    ]
