# Generated by Django 5.0.1 on 2024-01-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("screener", "0003_remove_stockdata_screener_st_m1_e43f8c_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="timezone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
